USE CORREOS_MASIVOS;
CREATE TABLE clientes (
  ID_RUT MEDIUMINT,
  ID_FLEXIBILIDAD INT,
  ID_REPRESENTANTE_LEGAL INT,
  ID_LIMITE_CONSUMO INT,
  ID_REGION INT,
  ID_NECESIDADES_EMPRESA INT,
  PRIMARY KEY (ID_RUT)
);
CREATE TABLE rut (
  ID_RUT MEDIUMINT PRIMARY KEY,
  RAZON_SOCIAL VARCHAR(255),
  TELEFONO VARCHAR(20),
  CORREO VARCHAR(255),
  ANTIGUEDAD INT,
  CARTERIZADO BIT
);
CREATE TABLE REPRESENTANTE_LEGAL (ID_RUT MEDIUMINT PRIMARY KEY, 
RUT MEDIUMINT, TELEFONO INT);

CREATE TABLE flexibilidad_documental (
  ID_FLEX_DOCUMENTAL INT PRIMARY KEY,
  EMPRESA_EN_UN_DIA BIT,
  EMPRESA_EN_CONSERVATORIO BIT
);
ALTER TABLE flexibilidad_documental
MODIFY COLUMN EMPRESA_EN_UN_DIA VARCHAR(255),
MODIFY COLUMN EMPRESA_EN_CONSERVATORIO VARCHAR(255);

CREATE TABLE REGIÓN ( ID_REGIÓN VARCHAR(255),
 COMUNA VARCHAR(255) , 
 CALLE VARCHAR(255));
 
CREATE TABLE LIMITE_DE_CONSUMO (ID_LC INT, LC_MOVIL INT, LC_CONSUMO_SSPP INT);

CREATE TABLE NECESIDADES_DE_LA_EMPRESA( ID_PRODUCTOS VARCHAR(255), 
VOZ VARCHAR (255), 
SSPP VARCHAR (255));


